# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {} is {} kilometers.'.format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
print('an array of 10 zeros:',np.zeros(10))

an array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print('an array of 10 fives:',np.ones(10)*5)

an array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
print('an array of all the even integers from 20 to 35:', np.arange(20,35,2))

an array of all the even integers from 20 to 35: [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd
data={'Name':['karthika','narmatha','sabari'],
      'Mark':[80,90,100]}
df=pd.DataFrame(data)
df

Name  Mark
0  karthika    80
1  narmatha    90
2    sabari   100

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
start_date = datetime.datetime(2023,1,1)
print("The original date is :"+ str(start_date))
K=10
res=[start_date + datetime.timedelta(days=idx) for idx in range(K)]
print("Next K dates list:"+ str(res))

The original date is :2023-01-01 00:00:00
Next K dates list:[datetime.datetime(2023, 1, 1, 0, 0), datetime.datetime(2023, 1, 2, 0, 0), datetime.datetime(2023, 1, 3, 0, 0), datetime.datetime(2023, 1, 4, 0, 0), datetime.datetime(2023, 1, 5, 0, 0), datetime.datetime(2023, 1, 6, 0, 0), datetime.datetime(2023, 1, 7, 0, 0), datetime.datetime(2023, 1, 8, 0, 0), datetime.datetime(2023, 1, 9, 0, 0), datetime.datetime(2023, 1, 10, 0, 0)]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df2=pd.DataFrame(lists,columns=['S.No','Name','Age'])
print(df2)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
